application: nonoel
version: 1
runtime: go
api_version: go1

handlers:
- url: /REST/.*
  script: _go_app
  secure: always
- url: /
  static_files: webapp/index.html
  secure: always
  upload: webapp/index.html
- url: /
  static_dir: webapp
  secure: always
