application: nonoel
version: 1
runtime: go
api_version: go1

handlers:
- url: /(un)?authenticated-resources/.*
  script: _go_app
  secure: always
- url: /
  static_files: src/webapp/index.html
  secure: always
  upload: src/webapp/index.html
- url: /
  static_dir: src/webapp
  secure: always
